export interface FundLiveData { schemeCode:number; schemeName:string; nav:number; navDate:string; navChange1d:number; return1w:number; return1m:number; return3m:number; return6m:number; return1y:number; source:"MFAPI"; fetchedAt:string; }
type SearchItem={schemeCode:number;schemeName:string}; type NavPoint={date:string;nav:string}; type HistoryResponse={data?:NavPoint[]};
const cache=new Map<string,{expires:number;data:FundLiveData}>(); const CACHE_MS=10*60*1000;
function norm(s:string){return s.toLowerCase().replace(/[^a-z0-9]+/g," ").replace(/\b(plan|option|growth|direct|regular)\b/g," ").replace(/\s+/g," ").trim();}
function parseDate(v:string){const m=v.match(/^(\d{2})-(\d{2})-(\d{4})$/);return m?new Date(`${m[3]}-${m[2]}-${m[1]}T00:00:00+05:30`):null;}
function navAtOrBefore(data:NavPoint[],days:number,latest:Date){const target=new Date(latest);target.setDate(target.getDate()-days);let best:{date:Date;nav:number}|null=null;for(const p of data){const date=parseDate(p.date),nav=Number(p.nav);if(!date||!Number.isFinite(nav)||date>target)continue;if(!best||date>best.date)best={date,nav};}return best?.nav??null;}
async function searchScheme(name:string):Promise<SearchItem>{const r=await fetch(`https://api.mfapi.in/mf/search?q=${encodeURIComponent(name)}`,{cache:"no-store",headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`MFAPI search failed: ${r.status}`);const items=await r.json() as SearchItem[];if(!Array.isArray(items)||!items.length)throw new Error(`MFAPI scheme not found: ${name}`);return items.find(x=>norm(x.schemeName)===norm(name))??items.find(x=>/direct/i.test(x.schemeName)&&/growth/i.test(x.schemeName))??items[0];}
export async function fetchFundLiveData(name:string):Promise<FundLiveData>{const cached=cache.get(name);if(cached&&cached.expires>Date.now())return cached.data;const scheme=await searchScheme(name);const r=await fetch(`https://api.mfapi.in/mf/${scheme.schemeCode}`,{cache:"no-store",headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`MFAPI history failed for ${scheme.schemeCode}: ${r.status}`);const json=await r.json() as HistoryResponse;const history=Array.isArray(json.data)?json.data:[];const ordered=history.map(p=>({...p,parsed:parseDate(p.date),numeric:Number(p.nav)})).filter(p=>p.parsed&&Number.isFinite(p.numeric)).sort((a,b)=>a.parsed!.getTime()-b.parsed!.getTime());const latest=ordered.at(-1);if(!latest)throw new Error(`MFAPI returned invalid NAV history for ${scheme.schemeCode}`);const latestDate=latest.parsed!,ret=(days:number)=>{const prior=navAtOrBefore(history,days,latestDate);return prior?((latest.numeric/prior)-1)*100:0;};const data={schemeCode:scheme.schemeCode,schemeName:scheme.schemeName,nav:Number(latest.numeric.toFixed(4)),navDate:latest.date,navChange1d:ret(1),return1w:ret(7),return1m:ret(30),return3m:ret(90),return6m:ret(180),return1y:ret(365),source:"MFAPI" as const,fetchedAt:new Date().toISOString()};cache.set(name,{expires:Date.now()+CACHE_MS,data});return data;}
export async function fetchFundsLive(names:string[]){const unique=[...new Set(names.filter(Boolean))];const results=await Promise.allSettled(unique.map(async name=>[name,await fetchFundLiveData(name)] as const));const entries:[string,FundLiveData][]=[];for(const result of results){if(result.status==="fulfilled")entries.push(result.value);else console.warn("MFAPI live NAV unavailable for one mapped fund",result.reason);}return new Map(entries);}
