// Deterministic market-opportunity scoring from validated live index data.

export interface MarketData { sectorKey:string; currentLevel:number; todayChange:number; weekChange:number; monthChange:number; threeMonthChange:number; sixMonthChange:number; yearChange:number; high52w:number; low52w:number; dayHigh:number; dayLow:number; rsi14:number; macd:number; macdSignal:number; macdHistogram:number; dma20:number; dma50:number; dma100:number; dma200:number; adx:number; volumeTrend:"increasing"|"decreasing"|"stable"; lastUpdated:string; }
export type DecisionAction = "BUY" | "BUY ON DIP" | "SIP" | "WATCH" | "AVOID";
export interface SectorScores { correctionScore:number; technicalScore:number; bullBearScore:number; valuationScore:number; reasonScore:number; historicalCorrectionScore:number; marketBreadthScore:number; fallQualityScore:number; opportunityScore:number; riskScore:number; action:DecisionAction; bullBearLabel:string; reasonForFall:string; reasonCategory:string; explanation:string; historicalPercentile:number; }
export interface ScoringWeights { correction:number; technical:number; bullBear:number; valuation:number; reasonForFall:number; historicalCorrection:number; marketBreadth:number; }
export const DEFAULT_WEIGHTS: ScoringWeights = { correction:20, technical:20, bullBear:20, valuation:15, reasonForFall:10, historicalCorrection:10, marketBreadth:5 };
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
export function calcCorrectionScore(d:MarketData){const a=clamp(Math.abs(Math.min(d.todayChange,0))*15,0,30),b=clamp(Math.abs(Math.min(d.weekChange,0))*5,0,20),c=clamp(Math.abs(Math.min(d.monthChange,0))*3,0,20),e=clamp(Math.abs(Math.min(d.threeMonthChange,0))*2,0,15),h=d.high52w>0?((d.high52w-d.currentLevel)/d.high52w)*100:0;return Math.round(clamp(a+b+c+e+clamp(h*2,0,15),0,100));}
export function calcTechnicalScore(d:MarketData){let s=50;if(d.rsi14<30)s+=20;else if(d.rsi14<40)s+=12;else if(d.rsi14<50)s+=5;else if(d.rsi14>70)s-=15;else if(d.rsi14>60)s-=5;s+=d.macdHistogram>0?8:-5;s+=d.currentLevel>d.dma200?10:-10;s+=d.currentLevel>d.dma50?5:-5;if(d.adx>25)s+=5;return Math.round(clamp(s,0,100));}
export function calcBullBearScore(d:MarketData){let s=50;s+=d.currentLevel>d.dma200?15:-15;s+=d.currentLevel>d.dma50?10:-10;s+=d.currentLevel>d.dma20?5:-5;s+=d.dma50>d.dma200?10:-10;if(d.rsi14>40&&d.rsi14<60)s+=5;s+=d.yearChange>0?10:-5;s+=d.threeMonthChange>0?5:-3;return Math.round(clamp(s,0,100));}
export function calcValuationScore(d:MarketData){const h=d.high52w>0?((d.high52w-d.currentLevel)/d.high52w)*100:0,l=d.low52w>0?((d.currentLevel-d.low52w)/d.low52w)*100:0;let s=50;if(h>20)s+=25;else if(h>15)s+=20;else if(h>10)s+=12;else if(h>5)s+=5;if(l<10)s+=10;else if(l>50)s-=10;if(d.monthChange<-5)s+=8;if(d.threeMonthChange<-10)s+=7;return Math.round(clamp(s,0,100));}
export function analyzeReasonForFall(d:MarketData,all:MarketData[]){const a=all.filter(x=>x.todayChange!==0||x.sectorKey===d.sectorKey),avg=a.reduce((s,x)=>s+x.todayChange,0)/Math.max(a.length,1),fall=a.filter(x=>x.todayChange<-.5).length,broad=fall/Math.max(a.length,1)>.6;if(broad&&Math.abs(d.todayChange-avg)<1.5)return{reason:"Broad market correction is affecting most tracked indices, suggesting a market-wide risk-off move rather than an isolated sector event.",category:"MARKET-WIDE FALL",score:80};if(d.todayChange<-3&&d.yearChange>15)return{reason:"The index has had a strong one-year run and today's decline is consistent with profit booking after an extended advance.",category:"PROFIT BOOKING",score:75};if(!broad&&d.todayChange<avg-2)return{reason:"The sector is materially underperforming the tracked market, consistent with sector rotation or a sector-specific catalyst.",category:"SECTOR ROTATION",score:60};if(d.todayChange<-2&&d.threeMonthChange<-15)return{reason:"Weakness has persisted across multiple months, increasing the probability that the decline is structural rather than a one-day correction.",category:"STRUCTURAL / MACRO",score:45};if(d.todayChange<-1&&d.currentLevel<d.dma200)return{reason:"The index is below its long-term trend while falling further, so the correction needs confirmation before capital is deployed aggressively.",category:"STRUCTURAL WEAKNESS",score:30};return{reason:"Live price and trend data do not provide enough evidence to classify the catalyst with confidence.",category:"INSUFFICIENT EVIDENCE",score:55};}
export function calcFallQualityScore(d:MarketData,b:number,v:number,r:number){let s=d.currentLevel>d.dma200?25:5;s+=v*.25;if(d.rsi14<35)s+=15;else if(d.rsi14<45)s+=8;s+=r*.15;s+=b*.1;return Math.round(clamp(s,0,100));}
export function calcOpportunityScore(c:number,t:number,b:number,v:number,r:number,h:number,m:number,w:ScoringWeights=DEFAULT_WEIGHTS){const total=Object.values(w).reduce((a,x)=>a+x,0);return Math.round(clamp((c*w.correction+t*w.technical+b*w.bullBear+v*w.valuation+r*w.reasonForFall+h*w.historicalCorrection+m*w.marketBreadth)/total,0,100));}
export function calcRiskScore(d:MarketData,b:number){let r=30;if(d.currentLevel<d.dma200)r+=20;if(d.rsi14<25)r+=10;if(d.threeMonthChange<-15)r+=15;if(b<40)r+=15;if(d.adx>30&&d.todayChange<-2)r+=10;return Math.round(clamp(r,0,100));}
export function determineAction(o:number,r:number,b:number,f:number,t:number):DecisionAction{if(r>=75|| (o<40&&b<40))return "AVOID";if(o>=78&&r<50&&b>=60&&f>=70)return "BUY";if(o>=65&&r<65&&f>=55)return t< -1.5?"BUY ON DIP":"SIP";if(o>=50&&r<75)return "SIP";return "WATCH";}
export function getBullBearLabel(s:number){if(s>=80)return"Strong Bullish";if(s>=60)return"Bullish";if(s>=40)return"Neutral";if(s>=20)return"Bearish";return"Strong Bearish";}
export function calcHistoricalCorrectionScore(t:number){const a=Math.abs(t);let p=25;if(a>5)p=97;else if(a>4)p=94;else if(a>3)p=88;else if(a>2)p=78;else if(a>1.5)p=68;else if(a>1)p=55;else if(a>.5)p=40;return{score:p,percentile:p};}
export function generateExplanation(name:string,d:MarketData,s:Omit<SectorScores,"explanation">){const p=[`${name} moved ${d.todayChange>=0?"up":"down"} ${Math.abs(d.todayChange).toFixed(2)}% today.`];p.push(s.bullBearScore>=60?`Trend remains ${s.bullBearLabel.toLowerCase()}.`:s.bullBearScore>=40?"Trend is neutral around its moving-average structure.":"The index is below its longer-term trend, so risk remains elevated.");if(d.rsi14<35)p.push(`RSI is oversold at ${d.rsi14.toFixed(1)}.`);p.push(s.reasonForFall);p.push(s.action==="BUY"?"Conclusion: the live setup supports a direct allocation.":s.action==="BUY ON DIP"?"Conclusion: the setup is attractive on weakness; stagger the allocation.":s.action==="SIP"?"Conclusion: use a staggered SIP-style allocation rather than a one-shot entry.":s.action==="AVOID"?"Conclusion: avoid fresh allocation until risk conditions improve.":"Conclusion: wait for confirmation before committing capital.");return p.join(" ");}
export function calculateAllScores(d:MarketData,all:MarketData[],weights?:ScoringWeights):SectorScores{const c=calcCorrectionScore(d),t=calcTechnicalScore(d),b=calcBullBearScore(d),v=calcValuationScore(d),rr=analyzeReasonForFall(d,all),h=calcHistoricalCorrectionScore(d.todayChange),m=all.filter(x=>x.todayChange>0).length/Math.max(all.length,1)*100,f=calcFallQualityScore(d,b,v,rr.score),o=calcOpportunityScore(c,t,b,v,rr.score,h.score,m,weights),r=calcRiskScore(d,b),action=determineAction(o,r,b,f,d.todayChange),label=getBullBearLabel(b),partial={correctionScore:c,technicalScore:t,bullBearScore:b,valuationScore:v,reasonScore:rr.score,historicalCorrectionScore:h.score,marketBreadthScore:Math.round(m),fallQualityScore:f,opportunityScore:o,riskScore:r,action,bullBearLabel:label,reasonForFall:rr.reason,reasonCategory:rr.category,historicalPercentile:h.percentile};return{...partial,explanation:generateExplanation(d.sectorKey,d,partial)};}
