"use client";

import { useState, useEffect } from "react";
import type { ScoredSector } from "@/lib/types";
import { SECTORS } from "@/lib/sectors";

interface PortfolioData { holdings: Array<{ sectorKey:string; sectorName:string; role:string; category:string; targetWeight:number; investedAmount:number; currentValue:number; actualWeight:number; deviation:number; status:string; fundName:string; }>; totalInvested:number; totalCurrentValue:number; absoluteReturn:number; returnPct:number; todayPnL:number; }
interface Props { sectors: ScoredSector[]; }
const CATEGORY_LABELS: Record<string,{label:string;color:string}> = { core:{label:"CORE",color:"text-blue-400"}, sector:{label:"SECTOR / TACTICAL",color:"text-purple-400"}, defensive:{label:"DEFENSIVE",color:"text-terminal-yellow"} };

export default function PortfolioView({ sectors }: Props) {
  const [portfolio,setPortfolio] = useState<PortfolioData|null>(null); const [addingFund,setAddingFund]=useState<string|null>(null); const [investAmount,setInvestAmount]=useState("");
  useEffect(()=>{ fetch("/api/portfolio").then(r=>r.json()).then(setPortfolio).catch(console.error); },[]);
  const refresh=async()=>{ const r=await fetch("/api/portfolio"); setPortfolio(await r.json()); };
  const add=async(key:string)=>{ const amt=parseFloat(investAmount); if(!amt||amt<=0)return; const s=SECTORS.find(x=>x.key===key); await fetch("/api/portfolio",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sectorKey:key,investedAmount:amt,fundName:s?.recommendedFund})}); setAddingFund(null);setInvestAmount("");await refresh(); };
  const display=portfolio?.holdings?.length?portfolio.holdings:SECTORS.map(s=>({sectorKey:s.key,sectorName:s.name,role:s.role,category:s.category,targetWeight:s.targetWeight,investedAmount:0,currentValue:0,actualWeight:0,deviation:-s.targetWeight,status:"UNDERWEIGHT",fundName:s.recommendedFund}));
  const invested=portfolio?.totalInvested||0, value=portfolio?.totalCurrentValue||0, ret=portfolio?.absoluteReturn||0, retPct=portfolio?.returnPct||0;
  return <div className="space-y-5 fade-in">
    <section className="glass-card rounded-xl p-5">
      <div className="flex flex-wrap items-end justify-between gap-3 mb-5"><div><div className="flex items-center gap-2"><span className="text-blue-400">▣</span><h2 className="text-sm font-bold uppercase tracking-[.12em]">My Long-Term Portfolio</h2></div><p className="text-[9px] text-terminal-text-muted mt-1">Target allocation · actual exposure · rebalancing discipline</p></div><span className="text-[9px] uppercase tracking-wider text-terminal-text-muted">Live portfolio state</span></div>
      <div className="grid grid-cols-2 lg:grid-cols-5 gap-3 mb-6">{[["Invested",`₹${invested.toLocaleString("en-IN")}`,"text-terminal-text"],["Current Value",`₹${value.toLocaleString("en-IN")}`,"text-terminal-text"],["Returns",`${ret>=0?"+":"-"}₹${Math.abs(ret).toLocaleString("en-IN")}`,ret>=0?"text-terminal-green":"text-terminal-red"],["Return %",`${retPct.toFixed(2)}%`,retPct>=0?"text-terminal-green":"text-terminal-red"],["Today's P&L",`₹${portfolio?.todayPnL||0}`,"text-terminal-text"]].map(([a,b,c])=><div key={a} className="rounded-lg border border-terminal-border bg-[#090f18] p-3"><p className="text-[8px] uppercase tracking-wider text-terminal-text-muted">{a}</p><p className={`text-lg font-bold font-mono mt-1 ${c}`}>{b}</p></div>)}</div>
      <div className="grid grid-cols-1 xl:grid-cols-[290px_1fr] gap-6">
        <div className="terminal-panel p-4"><p className="text-[9px] uppercase tracking-wider text-terminal-text-muted mb-2">Target Allocation</p><div className="flex justify-center"><svg viewBox="0 0 200 200" width="210" height="210">{(()=>{let c=0;const colors=["#3b82f6","#6366f1","#8b5cf6","#06b6d4","#22c55e","#84cc16","#eab308","#f97316","#ef4444","#ec4899","#14b8a6"];return SECTORS.map((s,i)=>{const p=s.targetWeight/100,sa=c*360,ea=(c+p)*360;c+=p;const a=polar(100,100,78,sa),b=polar(100,100,78,ea),large=p>.5?1:0;return <path key={s.key} d={`M100 100 L${a.x} ${a.y} A78 78 0 ${large} 1 ${b.x} ${b.y} Z`} fill={colors[i%colors.length]} opacity=".85" stroke="#080d15" strokeWidth="1"/>})})()}<circle cx="100" cy="100" r="49" fill="#090f18"/><text x="100" y="97" textAnchor="middle" fill="#e8eef7" fontSize="12" fontWeight="700">TARGET</text><text x="100" y="114" textAnchor="middle" fill="#66778d" fontSize="9">100%</text></svg></div></div>
        <div className="overflow-x-auto">{(["core","sector","defensive"] as const).map(cat=>{const rows=display.filter(h=>h.category===cat);return <div key={cat} className="mb-5"><h3 className={`text-[10px] font-bold ${CATEGORY_LABELS[cat].color} tracking-[.12em] mb-2`}>{CATEGORY_LABELS[cat].label}</h3><table className="w-full min-w-[760px] text-[9px]"><thead><tr className="border-y border-terminal-border bg-[#090f18] text-terminal-text-muted uppercase tracking-wider"><th className="text-left p-2">Sector</th><th className="text-right p-2">Target</th><th className="text-right p-2">Actual</th><th className="text-right p-2">Invested</th><th className="text-right p-2">Value</th><th className="text-center p-2">Status</th><th className="text-center p-2">Add</th></tr></thead><tbody>{rows.map(h=><tr key={h.sectorKey} className="border-b border-terminal-border/60 hover:bg-blue-500/[.03]"><td className="p-2"><p className="font-semibold text-terminal-text">{h.sectorName}</p><p className="text-[8px] text-terminal-text-muted truncate max-w-[210px]">{h.fundName}</p></td><td className="p-2 text-right font-mono">{h.targetWeight}%</td><td className="p-2 text-right font-mono">{h.actualWeight.toFixed(1)}%</td><td className="p-2 text-right font-mono">₹{h.investedAmount.toLocaleString("en-IN")}</td><td className="p-2 text-right font-mono">₹{h.currentValue.toLocaleString("en-IN")}</td><td className="p-2 text-center"><span className={`px-1.5 py-0.5 rounded text-[8px] font-bold ${h.status==="OVERWEIGHT"?"bg-red-500/10 text-terminal-red":h.status==="UNDERWEIGHT"?"bg-yellow-500/10 text-terminal-yellow":"bg-green-500/10 text-terminal-green"}`}>{h.status}</span></td><td className="p-2 text-center">{addingFund===h.sectorKey?<div className="flex items-center justify-center gap-1"><input autoFocus type="number" value={investAmount} onChange={e=>setInvestAmount(e.target.value)} className="w-16 bg-terminal-bg border border-terminal-border rounded px-1 py-1 text-[9px]" placeholder="₹"/><button onClick={()=>add(h.sectorKey)} className="text-green-400">✓</button><button onClick={()=>setAddingFund(null)} className="text-terminal-text-muted">×</button></div>:<button onClick={()=>setAddingFund(h.sectorKey)} className="text-blue-400 hover:text-blue-300">+ Add</button>}</td></tr>)}</tbody></table></div>})}</div>
      </div>
      <div className="mt-2 pt-4 border-t border-terminal-border"><h3 className="text-[10px] font-bold uppercase tracking-wider text-terminal-text-muted mb-2">Rebalancing Alerts</h3><div className="space-y-1">{display.filter(h=>Math.abs(h.deviation)>5).map(h=><div key={h.sectorKey} className="flex flex-wrap items-center gap-2 text-[9px]"><span className={h.deviation>0?"text-terminal-red":"text-terminal-yellow"}>{h.deviation>0?"⬆":"⬇"}</span><span className="text-terminal-text">{h.sectorName}</span><span className="text-terminal-text-muted">Target: {h.targetWeight}%</span><span className="text-terminal-text-muted">Actual: {h.actualWeight.toFixed(1)}%</span><span className={h.deviation>0?"text-terminal-red":"text-terminal-yellow"}>{h.status}</span></div>)}{display.filter(h=>Math.abs(h.deviation)>5).length===0&&<span className="text-[9px] text-terminal-text-muted">No significant deviations detected.</span>}</div></div>
    </section>
  </div>;
}
function polar(cx:number,cy:number,r:number,deg:number){const a=((deg-90)*Math.PI)/180;return{x:cx+r*Math.cos(a),y:cy+r*Math.sin(a)};}
